### ISSUE TITLE
Log -in prompt when clicking Diderot link

### ISSUE THREAD

**Issue by kamyarghiam** [diderot-edu/diderot-feedback#104]
When I click on a Diderot link (for example a link to a post), it prompts me to re-log in into Diderot, even though I was already signed in. Even after I sign in, it takes me to the homepage rather than the link I clicked. Other people have reported the same problem. 

Known browsers that have this issue: Safari and Firefox.

**Comment by umutacar** [comment]
Forgot to close this.  Fixed...
