### ISSUE TITLE
Allow linking posts to an atom after they have been made

### ISSUE THREAD

**Issue by shiftsayan** [diderot-edu/diderot-feedback#110]
I do not think functionality like this currently exists, but I believe the ability to link a post to an atom even after it has been made can be useful. Sometimes students can forget to ask a question from within an atom and they might want to fix that or (probably more commonly) an instructor/TA might want to link the relevant atom to establish the connection and for other students to see it as a related post.

**Comment by umutacar** [comment]
This feature is available now from the Post's context menu item "Attach the post ..." 
(menu item should have been more concise...)

<img width="280" alt="image" src="https://user-images.githubusercontent.com/6068765/194151233-f6a2a135-97ad-45e1-bc89-6cc1a85e1669.png">
