### ISSUE TITLE
Incorrect calculation of open posts

### ISSUE THREAD

**Issue by mivkov** [diderot-edu/diderot-feedback#111]
![image](https://user-images.githubusercontent.com/19914400/115910286-a9471b00-a43a-11eb-9715-79d1304229f1.png)
![image](https://user-images.githubusercontent.com/19914400/115910304-ad733880-a43a-11eb-88ac-8ccc5e6935b2.png)

I took these two photos one after the other: it looks like clicking on closed posts calculates open posts as 0 (probably because there are none in that filtered view?). Is this expected behavior? Or should the number of open posts not depend on that filter?

**Comment by umutacar** [comment]
yes, this is the intended behavior.  open/close are relative to the filter.
