### ISSUE TITLE
Removing/reworking the warning when making posts/comments

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#119]
Hello! I was wondering if there could be an alternative to this warning that shows up when you click out of writing a post/comment:
![image](https://user-images.githubusercontent.com/43687061/141668567-60ce4e5a-5089-4c00-b658-4bd5a85347c6.png)

This ends up being more obtrusive than helpful in two main ways:
- Prevents highlighting & copying code or text from other comments or the original post
- Prevents clicking on any links - often I try to use Cmd + Click to open something linked in the original post in another tab for reference, but this prevents me from doing that

It'd be nice if this warning showed up less frequently, and optimally only when you're absolutely going to navigate away, i.e. clicking on a different post. Or if there was a way to say "Continue anyway" to dismiss the warning. 

Thanks!

**Comment by umutacar** [comment]
Thank you for this feedback. We will fix this.

**Comment by umutacar** [comment]
Refined to display the warning only when needed.
