### ISSUE TITLE
Allow instructors to change OP visibility

### ISSUE THREAD

**Issue by kopecs** [diderot-edu/diderot-feedback#120]
As an instructor it's useful to be able to change the original poster to be anonymous (use case: when threads which are initially private, and an instructor would like to make them public, but have the OP be anonymous).

This can currently be done by the OP, but not by instructors.

**Comment by umutacar** [comment]
For this use case, we could add "Everbody (Anon)" visibility option
When applied, this would make the post visible to everyone and anonymize the author
This approach could reduce user errors (forgetting to anonymize)

Would this be more preferable? 

We could separately allow anonymizing the author as well.

**Comment by kopecs** [comment]
That seems like a pretty reasonable solution to me.

**Comment by umutacar** [comment]
In the context menu (triple dots on RHS) there is now an "Anonymize ..." option 
(at the bottom)
This anonymizes all non-staff authors for the post + all comments
