### ISSUE TITLE
Changing visiblity settings applies to incorrect post

### ISSUE THREAD

**Issue by kopecs** [diderot-edu/diderot-feedback#121]
On occasion when changing the visibility setting for a post, the change is applied to the previously viewed post.

To reproduce:
- Select a post (A) in the post office
- Select another post (B) in the post office
- Change the visibility of that post (B)

Expected behaviour: visibility of B is changed.
Actual outcome: visibility of A is changed.

**Comment by umutacar** [comment]
Should be fixed
