### ISSUE TITLE
Anonymous posting and filtering

### ISSUE THREAD

**Issue by fredasu** [diderot-edu/diderot-feedback#123]
1) When I try to reply from the "Ask and Discuss", the Anonymous option is not available.
![image](https://user-images.githubusercontent.com/52425186/161885578-01ff9ef7-c1aa-4ed6-a4ba-444d640c91f7.png)

2) Filtering posts by assignment (ex: Written X) would be nice to avoid repeat questions instead of having to scroll through the "Ask and Discuss" of each section. Searching for posts looks for what the title/contents are and not what they're linked to, which isn't always helpful because people use very different naming conventions for titles...etc.

**Comment by umutacar** [comment]
Thank you for the bug catch and the suggestion.
The bug should be fixed now.
