### ISSUE TITLE
Long release delay

### ISSUE THREAD

**Issue by iliano** [diderot-edu/diderot-feedback#14]
I had a chapter (https://www.diderot.one/course/23/chapters/1568/) that was supposed to go live today at 9am.  At 9:30, my TAs informed me that it hadn't been released yet and we released it manually.

Could you check again that cron issue?  This is the same behavior as last time.

**Comment by umutacar** [comment]
I am not surprised.  Cron isn't robust in elastic environments like ours and ends up breaking after a number of scale-up/down  actions.  We are looking into implementing something more robust.

**Comment by umutacar** [comment]
Fixed.
