### ISSUE TITLE
Chapter ordering

### ISSUE THREAD

**Issue by iliano** [diderot-edu/diderot-feedback#15]
A student sent me the following feedback:

> A very small nitpick, but whenever the lectures are ordered from last to first down the page on the homepage of diderot, but when you click on one of them, it then switches from first to last ordering, which often causes misclicks when I want to then go to the next lecture notes.

[I tend to agree.  Letting the user decide if chapters should be ordered in ascending or descending order would be great.]

**Comment by umutacar** [comment]
Fixed.
