### ISSUE TITLE
Impossible to configure the hour at which an assignment is due

### ISSUE THREAD

**Issue by jonathan-laurent** [diderot-edu/diderot-feedback#16]
I created a new chapter.
I can configure the due date but not the time of the day at which it is due. It is set at 12:00 by default and I don't seem to be able to change that.

![Screenshot from 2020-08-28 17-07-49](https://user-images.githubusercontent.com/6361331/91615288-35a74980-e951-11ea-8325-084b06835242.png)

**Comment by umutacar** [comment]
Should be fixed.
