### ISSUE TITLE
Uploading/downloading lab handouts 

### ISSUE THREAD

**Issue by kamyarghiam** [diderot-edu/diderot-feedback#18]
In the TA view of Diderot, I created a new lab and uploaded a file with the extension ".tgz". The handout I uploaded was named "brutelab-handout.tgz"; however, when I tried to download the file after uploading it, the downloaded file was named "BruteLab-handout.tgz."

**Comment by umutacar** [comment]
what was the lab called?

**Comment by kamyarghiam** [comment]
BruteLab

**Comment by umutacar** [comment]
Gotcha!

**Comment by umutacar** [comment]
the file name is keyed by the lab name.  this seems more consistent.

**Comment by kamyarghiam** [comment]
I seeeee. Okay thanks!
