### ISSUE TITLE
Course settings: start-date

### ISSUE THREAD

**Issue by cgarrod** [diderot-edu/diderot-feedback#19]
Selecting a start date in the course settings seems to set the start date to the previous date, not the date selected

To reproduce:  
 1. Go to course settings on a new course.
 2. Select a new start date.
 3. Save settings.
 4. Browse to course schedule (edit mode)

**Comment by umutacar** [comment]
should be fixed.  thanks for noticing this and the schedule issue.  it was due to an implicit time zone translation.
