### ISSUE TITLE
Solutions are not shown to students anymore after they submit 

### ISSUE THREAD

**Issue by jonathan-laurent** [diderot-edu/diderot-feedback#23]
We released a "submittable chapter" two weeks ago and checked the "Is solutions published" box.
However, since the Diderot update, students do not see the solutions anymore when they submit:

<img width="1277" alt="Screen Shot 2020-08-30 at 10 27 39 PM" src="https://user-images.githubusercontent.com/6361331/91677221-11de3200-eb10-11ea-9c43-81cf9f779f26.png">

**Comment by umutacar** [comment]
should be fixed.
