### ISSUE TITLE
Announcement email sent even with option unchecked

### ISSUE THREAD

**Issue by elucidium** [diderot-edu/diderot-feedback#24]
Email notifications for course-wide announcements seem to be getting delivered even with the "Send an email notification to everyone." option unchecked. (I've confirmed this with a student and some other TAs.)

**Comment by umutacar** [comment]
The notification settings controls this even if the author of the announcement does not send notifications.

Each user has a notifications setting (see the menu under the bell).  This controls the notifications for each user.  By default, send email when there is an announcement is on.
