### ISSUE TITLE
Nice comment doesn't update

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#26]
When giving "Nice Comment/Thanks" to a comment, the UI doesn't update until after the page is refreshed

Before:
![image](https://user-images.githubusercontent.com/43687061/91680401-ba8c9180-eb10-11ea-9355-9bd6bd3cbbeb.png)

Clicked but no update:
![image](https://user-images.githubusercontent.com/43687061/91680353-8e711080-eb10-11ea-9aa9-2cd5482362c9.png)

After refresh:
![image](https://user-images.githubusercontent.com/43687061/91680373-9df05980-eb10-11ea-9c28-e77f2904730a.png)

**Comment by umutacar** [comment]
should be fixed now.
