### ISSUE TITLE
0 is not allowed anymore as a chapter number

### ISSUE THREAD

**Issue by jonathan-laurent** [diderot-edu/diderot-feedback#28]
Diderot used to accept 0 as a chapter number (now called "rank"). However, it is now complaining about it:

![Screenshot from 2020-08-31 13-16-50](https://user-images.githubusercontent.com/6361331/91748828-953e6880-eb8e-11ea-8ce8-ef3bc33017e8.png)

Would it be possible to allow 0 as a chapter number again?
I think there is a good case for it as several classes offer preparatory assignments called  "Lab 0" or "Assignment 0".

**Comment by umutacar** [comment]
Chapters are now resortable
