### ISSUE TITLE
When loading a question which has comments on it, the comments will not show

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#29]
Sometimes when loading a post, the comments will briefly appear, and then disappear. This can be seen with the following 15210 post: https://www.diderot.one/courses/44/post-office/21203

**Comment by ishantheperson** [comment]
![913A5289-DB58-4FB7-BF0F-BE0616C8EE41](https://user-images.githubusercontent.com/1707565/91927611-d322b600-ec8e-11ea-9162-bcf21eb29e6d.jpeg)

**Comment by umutacar** [comment]
should be fixed.  there is still a corner case that might come up on older browsers but let's see how common that is...

**Comment by ishantheperson** [comment]
@umutacar If humanities courses can charge $100 for a textbook then surely we can require people to update to the latest version of their browser 😂
