### ISSUE TITLE
Email always sent when posting announcements.

### ISSUE THREAD

**Issue by gauravmm** [diderot-edu/diderot-feedback#3]
When posting an announcement, I get an email even if I uncheck the "send an email" option.

**Comment by ada-anil** [comment]
Your personal notifications settings, by default, is such that you get an email for announcements. Can you check if your setting is to receive emails for announcements?

**Comment by gauravmm** [comment]
I'd like to be able to put up announcements without sending an email out, even if users have opted-in to receiving them.

**Comment by ada-anil** [comment]
If I was a student, I wouldn't like it if I wanted to receive email notifications, but somehow those settings could be overridden so that I do not receive the email. It makes sense to override it so that they are forced to receive the email, but the other way around would be very confusing (students would probably report it as a bug).

**Comment by gauravmm** [comment]
I realized that is is because I use announcements for two separate use-cases:

1. To promulgate a message to all users, usually in a time-sensitive context
2. To aggregate information in one location and direct some users to it in response to questions they post.

I want to send emails for the former but not the latter. How should I handle the latter?

**Comment by ada-anil** [comment]
I see. Let me think about it.

**Comment by umutacar** [comment]
It sound like what you want is to be able to create "communique" for the purposes of referencing this.  

* One possibility is to add a post type called a "communique" or "note" or "remarks" or something that serves this purpose.  These would only have a "onsite" existence and would not be emailed/notified.  

* Another possibility is  to create a "Book" and simply add to this book the communiques, which can then be referred to, discussed (by creating posts on them) etc.  The advantage of this is this itself becomes part of the course content.  You can create them by using a simple WYSIWYG editor onsite.

**Comment by gauravmm** [comment]
I am in favor of a "note" option.
