### ISSUE TITLE
When viewing a post on mobile, the post loads at the bottom of the page

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#31]
Really appreciate the new responsive design. However, when clicking on a post on mobile, the content loads at the bottom of the page. This leads users to believe the content is not loading/is broken, and is otherwise quite inconvenient 

Expected behavior:
 - The page should jump down to the content when someone selects a question 
 - (Better) The content should load in its position in the list.

**Comment by umutacar** [comment]
The better option has been on the TODO deck.

**Comment by umutacar** [comment]
this should be better now.
