### ISSUE TITLE
When viewing the staff page as a TA, my regular name is shown instead of my “professional name”

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#32]
The profile picture is correct however 

![913A5289-DB58-4FB7-BF0F-BE0616C8EE41](https://user-images.githubusercontent.com/1707565/91927611-d322b600-ec8e-11ea-9162-bcf21eb29e6d.jpeg)

**Comment by kopecs** [comment]
Assuming your regular name is Stuart Little, this holds for viewing the staff page as a student too.

**Comment by umutacar** [comment]
Should be fixed.
