### ISSUE TITLE
Unnecessary horizontal scroll bar in post list

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#34]
The div which holds the list of all posts made has `overflow: auto!important` set, when it should be `overflow-y: auto!important` (hopefully eventually without `!important` :) )

![image](https://user-images.githubusercontent.com/1707565/91931079-521bec80-ec97-11ea-8a12-463734026419.png)

**Comment by umutacar** [comment]
should be fixed.
