### ISSUE TITLE
Images overflow the content area when viewing a question

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#35]
Expected behavior: The image should be scaled to fit the area. Users who need to view it at full resolution can right click -> open in new tab 

![image](https://user-images.githubusercontent.com/1707565/92020175-9ac1bd00-ed0c-11ea-99e4-916cc1f90237.png)

**Comment by ishantheperson** [comment]
This also applies to comments:
![image](https://user-images.githubusercontent.com/1707565/92020726-72868e00-ed0d-11ea-821e-324e1f085ecf.png)

This can be fixed by applying the CSS `max-width: 100%` to these `img` tags

**Comment by umutacar** [comment]
should be fixed.
