### ISSUE TITLE
The editor's quotation tool does not render appropriately

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#38]
When using the quote tool in the text editor, the content looks fine in the preview, but renders as HTML tags in the output:
![image](https://user-images.githubusercontent.com/1707565/92023307-73212380-ed11-11ea-93ad-89a5a43247a5.png)
![image](https://user-images.githubusercontent.com/1707565/92023335-7ae0c800-ed11-11ea-9dd3-4bab4402d221.png)

**Comment by umutacar** [comment]
should be fixed.
