### ISSUE TITLE
Update chapter PDF after released

### ISSUE THREAD

**Issue by RiaPradeep** [diderot-edu/diderot-feedback#44]
Would it be possible to be able to update a chapter's pdf file after it's been released without having to retract and re-release the chapter? It would be useful to fix typos, add forgotten elements, etc. 

Currently the option to update the pdf source of a released chapter is greyed out.
Edit: It also doesn't work through the Diderot CLI (it says the chapter is uploaded successfully but the change isn't reflected)

**Comment by umutacar** [comment]
Good point.  It should be possible to do this.  Will look into it.

**Comment by umutacar** [comment]
this is done.
