### ISSUE TITLE
Unable to scroll posts on mobile

### ISSUE THREAD

**Issue by cmax4jam** [diderot-edu/diderot-feedback#48]
When viewing posts on the posts landing page, I am unable to both scroll to see more posts on the left sidebar as well as scrolling to see more content of the currently viewed post.  See screenshot.  This is on an iPad.

<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/7969362/92334190-c66cdc00-f059-11ea-8b4f-e452a2780f55.png">

**Comment by ishantheperson** [comment]
I am having the same issue on my iPad. I find that the rest of the Diderot interface works quite well on a tablet so I hope this gets fixed soon

**Comment by umutacar** [comment]
does this happen only in horizontal mode? or does it also happen in vertical mode? 

also do you know if it happens if it happen with Chrome and Safari?

**Comment by cmax4jam** [comment]
@umutacar Yes, this happens in both horizontal and vertical mode (portrait/landscape) and on both chrome and safari on mobile (iPad).

**Comment by ishantheperson** [comment]
It occurs in both orientations. This is on iOS, so chrome and safari are using the same rendering engine. However the screenshot above is in safari for iOS and I am using chrome for iOS

**Comment by umutacar** [comment]
This should be fixed.  Sorry about the delay.
