### ISSUE TITLE
Data URLs in notification emails

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#49]
I am guessing this is coming from when a student pastes an image into the editor. 
![image](https://user-images.githubusercontent.com/1707565/92339874-17d29680-f06d-11ea-90aa-fbfb954830b6.png)

The image looks fine on the website
![image](https://user-images.githubusercontent.com/1707565/92339882-1ef9a480-f06d-11ea-828b-728d38705268.png)

**Comment by umutacar** [comment]
Are you using Gmail within your browser?

**Comment by ishantheperson** [comment]
Yes this is the regular gmail client at mail.google.com

**Comment by umutacar** [comment]
Yes, I have also noticed this.  If you "open" the email on its own window,
it doesn't do this.  Gmail has become dysfunctional recently so I
attributed it to that.   But maybe there is something we can do on our
end.

**Comment by umutacar** [comment]
Nevermind. Found a better way to do all this.

**Comment by ishantheperson** [comment]
Thats good to hear! I was going to say that Gmail probably limits the # of bytes shown in order to prevent against an attack where someone sends you a huge email, wasting bandwidth etc. The image could be stored on AWS or scaled down before sending it in the email

**Comment by umutacar** [comment]
Should be fixed
