### ISSUE TITLE
Can't enter time when setting chapter due date

### ISSUE THREAD

**Issue by RiaPradeep** [diderot-edu/diderot-feedback#50]
When setting a due date for a chapter, I can't enter a specific time. I can only adjust the hours/minutes of the due date by clicking the arrows (which only increments minutes by 5). For example, I can set a due date for 23:55 but not for 23:59.

This only appears to be an issue with setting due dates for chapters. I can set due dates for labs as expected.

**Comment by umutacar** [comment]
Should be fixed
