### ISSUE TITLE
Line breaks are dropped when copying the Autograder Output in the Labs tab

### ISSUE THREAD

**Issue by jonathan-laurent** [diderot-edu/diderot-feedback#51]
When I go to the Labs tab, the autograder feedback is rendered correctly:

<img width="1280" alt="Screen Shot 2020-09-07 at 1 58 00 PM" src="https://user-images.githubusercontent.com/6361331/92410480-32ab1680-f112-11ea-8080-1786ac350d8e.png">

However, if I copy the content of the "Autograder Output" box and paste it in any text editor, the line breaks aren't here anymore:

<img width="798" alt="Screen Shot 2020-09-07 at 2 00 05 PM" src="https://user-images.githubusercontent.com/6361331/92410549-769e1b80-f112-11ea-9190-635c9cc21161.png">

This is pretty puzzling.

**Comment by umutacar** [comment]
should be fixed.
