### ISSUE TITLE
Downloading all student submissions at once

### ISSUE THREAD

**Issue by jonathan-laurent** [diderot-edu/diderot-feedback#52]
There is currently a way to download individual student submissions as a JSON file.

Would it be possible to enable downloading a big archive with all student submissions?
Each submission file could be named after the name of the student.

Note: alternatively, it would already make a big difference for us if when downloading a student submission, the JSON file was named after the student rather that `submission.json`. This way, we only have to perform 25 clicks to download all 25 submissions. :-)

**Comment by umutacar** [comment]
This feature has been added.
