### ISSUE TITLE
Searching does not produce correct results

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#53]
One of our 122 assignments require students to find a post on Diderot and use it; however, the search results seem to not pop up correctly:

![image](https://user-images.githubusercontent.com/43687061/92418372-cee21700-f12c-11ea-9b7c-a92d475da290.png)

Right side is the post itself, left side shows no search results

**Comment by ishantheperson** [comment]
Have you tried doing it without the quotes?

**Comment by angelaz1** [comment]
Oops I used the wrong screenshot
It works with just Diderot and title: Diderot, but it doesn't work with:

> How to Use Diderot (Effectively)
> title: How to Use Diderot (Effectively)
> How to Use Diderot
> title: How to Use Diderot

which is what most students search

**Comment by umutacar** [comment]
this looks like bug.  it ought to work with those terms.

**Comment by umutacar** [comment]
if you use lowercase letters then the search succeeds.  if you use uppercase, it does not.  this is pretty strange.

**Comment by umutacar** [comment]
Should be fixed
