### ISSUE TITLE
Sort posts newest first by default

### ISSUE THREAD

**Issue by achanana** [diderot-edu/diderot-feedback#55]
As above, or give an option to choose a default. Right now posts are sorted unread first by default in the student-facing interface. Not sure if this is something that course instructors configure.

**Comment by umutacar** [comment]
You can now set your own personal default filters by clicking on the settings button right above "Search" on Post Office

![image](https://user-images.githubusercontent.com/6068765/98236048-b7f35180-1f30-11eb-8251-03fea2653aba.png)
