### ISSUE TITLE
Add explicit time zones to dates

### ISSUE THREAD

**Issue by RiaPradeep** [diderot-edu/diderot-feedback#56]
I guess Diderot automatically uses your current time zone, but adding explicit time zones could reduce some confusion, especially with remote learning. For example, I could specify a time zone along with the time when setting the due date for a lab and students could see the time zone along with the due date.

**Comment by umutacar** [comment]
This is coming soon, hopefully in time for Spring semester.

**Comment by umutacar** [comment]
This should be fixed.  Date/time displays time in user time in both the user's and the course's time zone (each course has a time zone, default US/New York)

![image](https://user-images.githubusercontent.com/6068765/105939970-38a18580-6028-11eb-80bf-341e64a43323.png)
