### ISSUE TITLE
Can't send email notification from draft posts

### ISSUE THREAD

**Issue by emjin** [diderot-edu/diderot-feedback#57]
I created an announcement, checking the "send email notifications to everyone" box, and saved it as a draft so I could share with other TAs for approval. However, when I posted, there was no notification (even for people who had email notifications on for all announcements). Also, the time stamp was of the time I created the draft, not made the post.

Would like there to be a persistent box for sending email notifications for drafts.

**Comment by umutacar** [comment]
should be fixed.
