### ISSUE TITLE
[Minor] Cannot scroll post office when a drop-down menu is open

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#59]
When sorting the post office by e.g. newest first, the menu does not disappear after selecting an option. This then prevents the user from scrolling, which is quite frustrating. 

Expected behavior:
 - Allow scrolling while a menu is open
 - Close the menu if a scroll event is detected
 - (Highly opinion based) Close the menu after an option is selected. However this option makes sense for some menus but not for others so I would not recommend it

**Comment by umutacar** [comment]
the sort selection allows you to sort in multiple dimensions.  For example, you can sort 
1) unread first
2) popular first
at the same time you will get unread first but they will be internally sorted from the most to the least popular one.

this is probably not apparent from the UI.  any ideas about how to best present this?

**Comment by ishantheperson** [comment]
I would put a number to the left of each menu item indicating which priority it takes when sorting. What metric does "popular" use? Generally course staffs will just pin any items which need to be seen by everyone so it may be less complicated to just not have that option.

**Comment by umutacar** [comment]
reorganized filters and sorts so that we don't need double sorting anymore.
