### ISSUE TITLE
[Suggestion] Make the post officer header section smaller to allow for more room for the post list

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#60]
Currently one can only view ~6 posts in the post office on a typical laptop screen. Meanwhile, the header/search bar seem to be quite large in comparison. A better use of screen real estate could be to have the post list take 100% of the page height and then move the header area to only take up the area above the post content area (i.e. a 2 column layout)

**Comment by umutacar** [comment]
Done
