### ISSUE TITLE
Can't see bookmarked posts

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#61]
There doesn't seem to be a section under "Bookmarks" for bookmarked posts from the post office

**Comment by umutacar** [comment]
wouldn't it be better to add this as a filter in the post office so that you can see it right there?  (like pinned).

**Comment by angelaz1** [comment]
Yes, that'd be a lot better!

**Comment by umutacar** [comment]
ok, good to hear.  we will do that.

-- Umut

**Comment by umutacar** [comment]
Fixed
