### ISSUE TITLE
Diderot note taking environment does not typeset Latex equations

### ISSUE THREAD

**Issue by kaashmonee** [diderot-edu/diderot-feedback#65]
In the notes section of each atom, enclosing math within $\LaTeX$ doesn't typeset after leaving the environment, resulting in something looking like this: 

![image](https://user-images.githubusercontent.com/12304593/93511242-7eb74180-f8f0-11ea-8b4d-5ef68708e8b6.png)

**Comment by MikeSha** [comment]
Seems to be we need something like quill editor or a preview like we have it for prompts.

@umutacar

Not sure what would be best, but preview will be easier I believe

**Comment by umutacar** [comment]
No need for the quill editor but something lightweight like the text box
and the preview would be great.  Preview would be best on a separate tab
because math will be used quite rarely I expect

**Comment by MikeSha** [comment]
Got it. Should be easy to implement

пт, 18 вер. 2020 о 17:04 Umut Acar <notifications@github.com> пише:

>
>
>
> No need for the quill editor but something lightweight like the text box
>
>
>
> and the preview would be great. Preview would be best on a separate tab
>
>
>
> because math will be used quite rarely I expect
>
>
>
>
>
>
>

**Comment by umutacar** [comment]
this should be fixed now.
