### ISSUE TITLE
Floating point error when assigning grades

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#68]
This looks quite unprofessional. I would recommend representing grades as integers and representing the values internally as scaled by 100x or something

![image](https://user-images.githubusercontent.com/1707565/93695082-bd532480-fac7-11ea-9fa9-bf0e22a3809c.png)

**Comment by umutacar** [comment]
Frontend us using rounding now. Like the idea of scaling.  This would be a bigger change but will keep this in mind.

**Comment by ishantheperson** [comment]
Sounds good, rounding is probably "good enough" but it does feel like a "band aid" fix.
