### ISSUE TITLE
Allow code to be selectable while grading

### ISSUE THREAD

**Issue by chairmanlu** [diderot-edu/diderot-feedback#74]
Currently when code grading, it doesn't appear possible to copy-paste code (e.g. if you want to test something or reformat to make it more readable). The only solution I've found is to reveal the student name and find their submission manually, which is not ideal.

**Comment by umutacar** [comment]
how about one of these
1) make it possible to download the file being graded,
2) copy the file contents to clipboard

**Comment by umutacar** [comment]
You can now copy code to clipboard by using the "copy to clipboard" button

![image](https://user-images.githubusercontent.com/6068765/98235362-b2493c00-1f2f-11eb-8889-b7b350cc28a4.png)
