### ISSUE TITLE
Slightly inconvenient poll results

### ISSUE THREAD

**Issue by mivkov** [diderot-edu/diderot-feedback#75]
Hi, would it be possible to change the text in poll results? For reference, the current results look like this:
![image](https://user-images.githubusercontent.com/19914400/97348144-231f9280-1864-11eb-8f62-ea1ec7a8820f.png)
where the format is x/y%, x being the number of voters for it and y being the percentage who voted for it. I found this a bit confusing because it feels like y should be the total number of voters when x/y is written. Would it be possible to have some format like "x votes: y% of all voters" (so, here it would be "1 vote: 3% of all voters" or something like that?

**Comment by umutacar** [comment]
you have found that "just a bit confusing" !!!  That is plain wrong.  Will fix it.

**Comment by umutacar** [comment]
should be fixed.
