### ISSUE TITLE
Search result returns an error

### ISSUE THREAD

**Issue by junhuih** [diderot-edu/diderot-feedback#76]
Hi,
The search functionality sometimes will return error. It is in-consistent when an error would be displayed. In the image, both error results from the same search term "look ahead" from different browsers. The first one is a completely newly opened browser with diderot account just logged in, the second one is the usual chrome browser I use.

![image](https://user-images.githubusercontent.com/37812261/98225817-2e736c00-1f90-11eb-9479-cf8362fbd3f6.png)
![image](https://user-images.githubusercontent.com/37812261/98225791-23b8d700-1f90-11eb-8e1d-055d9b6f5be7.png)
![image](https://user-images.githubusercontent.com/37812261/98225868-39c69780-1f90-11eb-8c7e-759fa8ba98eb.png)

**Comment by umutacar** [comment]
should be fixed.  sorry about that.
