### ISSUE TITLE
Diderot Keeps 404-ing

### ISSUE THREAD

**Issue by admidral** [diderot-edu/diderot-feedback#77]
When Im on a textbook sometimes after a few seconds it will 404 after it already loaded the page.

**Comment by umutacar** [comment]
Which chapter errors out?

**Comment by admidral** [comment]
https://diderot.one/courses/44/books/287/part/499/chapter/3525?toc=book
https://diderot.one/courses/44/books/287/part/499/chapter/3526?toc=book
It was these two (Bellman ford &Johnson algorithm from 210) that was doing it a lot at one point, I've seen many chapter error out from time to time

**Comment by umutacar** [comment]
Ok thank you.  Has this been happening recently (as of last week)?

**Comment by admidral** [comment]
It was happening a lot for about the hour before I posted. (Like it was in a loop of reload->loadpage error out) but mostly outside of that time its been fine, maybe 1 error per week or so.

**Comment by umutacar** [comment]
Ahh ok.  Good to hear.  An occasional 40x is ok because I am frequently
deploying updates.  When new code is deployed, the old code becomes defunct
and if cached (happens automatically in the browser) will lead to a 40x.

Please let me know if it gets worse.
