### ISSUE TITLE
"You have encountered an error" when trying to open posts

### ISSUE THREAD

**Issue by jlogs247** [diderot-edu/diderot-feedback#79]
When I try to access Diderot posts on google chrome, I am met with a screen that says "You have encountered an error" and "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.". There is also a button that says "Reload the application", and when pressed about 25% of the time it brings me to the post, and 75% of the time it just gives me the same error page. I have attached a picture of the screen. For some reason this doesn't happen when I use Diderot in an incognito chrome window.

<img width="1027" alt="Screen Shot 2020-12-03 at 11 36 11 PM" src="https://user-images.githubusercontent.com/63817674/101122419-7baf2180-35c0-11eb-9b61-388354509d36.png">

**Comment by umutacar** [comment]
it is likely one of your browser extensions.  could you try to turn them off one by one, see which one might be causing it?
