### ISSUE TITLE
Code grading rubric frequently drops keystrokes and selects wrong item sometimes

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#80]
If a student answer is completely correct, you want to hit several rubric items at once (e.g. 1 2 3). We expect all 3 rubric items to be selected, but what happens is that only one item "wins" and ends up selected (potential race condition?)

It's possible this only happens when there are more than 10 rubric items

**Comment by umutacar** [comment]
Should be fixed!
