### ISSUE TITLE
Grades csv exported from submittable chapters not uploadable in gradebook

### ISSUE THREAD

**Issue by khale** [diderot-edu/diderot-feedback#82]
@umutacar and I encountered this while walking through gradebook.

When you export a submittable chapter's scores as .csv, then upload that .csv directly into a gradebook, the upload fails with the attached error

![image](https://user-images.githubusercontent.com/466265/104822048-a3bbb280-5805-11eb-9a68-7d9f280d5d8d.png)

**Comment by umutacar** [comment]
Should be fixed
