### ISSUE TITLE
feature request: instructor/TA endorsements

### ISSUE THREAD

**Issue by khale** [diderot-edu/diderot-feedback#83]
It would be nice to be able to allow instructors/TAs to endorse specific student answers to questions as being good/correct ones. Or perhaps to be able to _promote_ a specific comment within a discussion to an answer.

**Comment by angelaz1** [comment]
I'd like to bump this feature request - as an instructor, it's very helpful for us to know which student answers have been verified by other instructors, and also endorse answers as a method to encourage students to answer more posts; as a student, it's helpful to know whether a student's answer has been verified by an instructor.

**Comment by umutacar** [comment]
This isdone.
