### ISSUE TITLE
mechanism for late submissions/individual deadline extensions

### ISSUE THREAD

**Issue by khale** [diderot-edu/diderot-feedback#85]
In submittable book chapters (i.e. for assignments/homeworks), it would be cool to have a way to:

1. Allow students to submit up to N days late (with submissions being marked as such in the submission management window)
2. Apply per-student deadline extensions for exceptional circumstances.

**Comment by umutacar** [comment]
we are working on this.  thank you for the feedback!

**Comment by umutacar** [comment]
submissions now support "due date" and "expiration date" and should accept late submissions after the due date and before the expiration date. 

it is possible to change the due date for individual students by creating a submission for them and then changing their due date via Manage/restart.  

we will switch this to a separate extension based system soon but this should work ok for now.

**Comment by khale** [comment]
Awesome!

**Comment by umutacar** [comment]
We also have rubric grading deployed now.  It is a bit rough around the edges but works ok.  we are grading our exam 1 by using these rubrics now.
