### ISSUE TITLE
Secondary email doesn't appear to verify/update properly

### ISSUE THREAD

**Issue by elucidium** [diderot-edu/diderot-feedback#86]
Upon entering an email address into the "Secondary email" field and hitting "Save Settings", the messages in the below screenshot pop up, and no verification email is sent to the indicated address. As a side note, this seems to also be the case for `...@andrew.cmu.edu` and `...@alumni.cmu.edu` addresses (according to the person who initially made me aware of this issue).

<img width="1791" alt="Screen Shot 2021-01-28 at 20 37 07" src="https://user-images.githubusercontent.com/8270776/106220027-9e1c8000-61a8-11eb-8e82-fdf296143e91.png">

**Comment by umutacar** [comment]
should be fixed.  sorry about that!
