### ISSUE TITLE
Editing post bug

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#87]
Editing (and potentially creating?) a post seems to cause a few weird things to happen
- Karma for the post disappears
- Mailbox icon on top left indicates there are x unread posts even when there aren't
- Discussion comments for the post disappear

It seems to treat the edited post as a brand new post. Refreshing the page reverts it to its previous (correct) state

Before Editing:
![image](https://user-images.githubusercontent.com/43687061/106372980-f08da600-633a-11eb-922c-e6c84c69c97f.png)
![image](https://user-images.githubusercontent.com/43687061/106372985-f4b9c380-633a-11eb-9f46-3d16e0de7006.png)

After Editing, no new posts were created:
![image](https://user-images.githubusercontent.com/43687061/106372996-026f4900-633b-11eb-91ad-dae548f98152.png)
![image](https://user-images.githubusercontent.com/43687061/106372999-069b6680-633b-11eb-943b-2cfff569a5e4.png)

**Comment by umutacar** [comment]
Thank you!

Discussions should show up again after editing the post.  Do they not? 

Re: new posts.  This indicates new posts, even if they may be filtered out by the current filters.  There were none indeed (even after clearing filters)?

**Comment by angelaz1** [comment]
Re: discussions. They currently do not show up. Instead, the indicator for new discussions appears. Clicking on the indicator causes the discussions to show up again

Before edit:
![image](https://user-images.githubusercontent.com/43687061/106373583-a6a7be80-6340-11eb-91fa-ac2b95faeec9.png)

After edit:
![image](https://user-images.githubusercontent.com/43687061/106373588-b2938080-6340-11eb-8448-17e448e4a5c3.png)

Re: new posts, there were no new posts before or while editing the post, even with the filters cleared

**Comment by umutacar** [comment]
ok thank you!   
regarding the posts likes: this might be a feature rather than a bug.  i think the thinking was that once a post in edited, we would not know how its meaning has changed.  for example, you might like a post now, but then i can change it in a way that you do not like anymore.  i will look into it though.

**Comment by umutacar** [comment]
should be better now.
