### ISSUE TITLE
problem connecting with zoom

### ISSUE THREAD

**Issue by RobertHarper** [diderot-edu/diderot-feedback#89]
I am messing around with Diderot, not yet seriously for a course, and tried to connect with Zoom.  It switches to another web page for Zoom with this error message displayed

Invalid client_id: zoom_client_id (4,702)

Dunno what this might mean, but that's what happens.

**Comment by umutacar** [comment]
zoom is not activated.  there are some hoops that we have to jump through unfortunately :(
