### ISSUE TITLE
[Suggestion] Clearer UI on visibility level of posts

### ISSUE THREAD

**Issue by angelaz1** [diderot-edu/diderot-feedback#91]
Currently, it's hard to immediately see the visibility level of posts (course staff/instructors only, or everyone). This makes it difficult for TAs/instructors when checking if a post is in the correct visibility level (i.e. for AIV purposes) or results in accidentally linking students to private posts that they can't access

It'd be nice to borrow some ideas from Piazza, where private questions are explicitly marked as such on the sidebar and a different "dark mode"-esque UI is used when reading a private post:
![image](https://user-images.githubusercontent.com/43687061/107991478-4d749780-6f9c-11eb-9b85-fbedac8a7d49.png)
![image](https://user-images.githubusercontent.com/43687061/107991488-51a0b500-6f9c-11eb-875e-b0bff16f3a13.png)

**Comment by umutacar** [comment]
thank you for the suggestion.  can do this.

**Comment by umutacar** [comment]
added icons indicating private and public posts.  hopefully this helps.
