### ISSUE TITLE
Search has no good indicator that the search is still in progress

### ISSUE THREAD

**Issue by duvallj** [diderot-edu/diderot-feedback#93]
This is what I see for about a second before the search completes:
![image](https://user-images.githubusercontent.com/10897431/109727483-6b3c2200-7b82-11eb-8b09-c9ef201a5142.png)
It is not clear the search hasn't completed yet, because the first thing I see is "total results: 0" rather than the very slowly animated dots. A progress bar (at the top??) shows up later, but that is also easy to miss in contrast to the results text.

Hiding "total results" text until the search completes or having "searching..." be there instead would be possible fixes.

**Comment by umutacar** [comment]
this should be better.
