### ISSUE TITLE
[Suggestion] Differentiate anonymous users within a post

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#95]
I have recently been arguing with a TA about some grading issues. Some other students also jumped in. However, everyone's name is "anonymous" so it is hard to tell who is who

![image](https://user-images.githubusercontent.com/1707565/110057445-71aed300-7d15-11eb-8ea9-6d9c76bdbec2.png)

It would be nice to have something like what Piazza has, where everyone is assigned a unique string. Note the use of numbers if more people have commented anonymously than strings are available:
![image](https://user-images.githubusercontent.com/1707565/110057530-9c992700-7d15-11eb-8765-716820ae47ec.png)

**Comment by ishantheperson** [comment]
Thanks for implementing this! I’ll go ahead and close this issue

**Comment by umutacar** [comment]
There is room for a bit more refinement but this should be an improvement over prior art.
