### ISSUE TITLE
latex table rendering

### ISSUE THREAD

**Issue by khale** [diderot-edu/diderot-feedback#96]
Not sure if I'm doing this correctly, but if I embed a table in a problem, it does not render correctly. For example,

```
\begin{problem}

    \begin{table}[]
        \begin{tabular}{lll|l}
            \textbf{A} & \textbf{B} & \textbf{C} & \textbf{Z} \\ \hline
            0          & 0          & 0          & 1          \\
            0          & 0          & 1          & 0          \\
            0          & 1          & 0          & 1          \\
            0          & 1          & 1          & 0          \\
            1          & 0          & 0          & 1          \\
            1          & 0          & 1          & 1          \\
            1          & 1          & 0          & 0          \\
            1          & 1          & 1          & 0
        \end{tabular}
    \end{table}

    \ask Write out a logical expression for the above
    truth table. You should write your expression in DNF (disjunctive
    normal form).

    ...
```

Renders as shown below (note the missing column/row delimiters). I've also tried wrapping the table in a `begin{atom}` but it doesn't seem to have an effect.

![image](https://user-images.githubusercontent.com/466265/110675245-49e9c000-8198-11eb-8c64-d6d5a1851852.png)

**Comment by umutacar** [comment]
the delimiters for `tabular` are not supported unfortunately.  

if you want to insert a table into an atom, use the tabular environment.  `table` and `figure` create atoms.  more info here
https://www.diderot.one/courses/15/books/46/chapter/421#atom-288755
